dist: trusty

language: node_js

node_js:
  - "10.14.2"

before_install:

install:

script:
  - npm run lint

deploy:
  provider: npm
  email: "ben@daostack.io"
  api_key: $NPM_API_TOKEN
  tag: next
  on:
    branch: master
